[9:20:07] Gracjan Polak: * Review ** TODO Remove ScriveChromeContentScriptAll.js from git This is a generated file, should not be there. ** TODO xmlHttpRequest.getAllResponseHeaders() does not exists Uncaught TypeError: undefined is not a function ** TODO IFrame container stopped working ** TODO Frameset container pops up a strange dialog box "While initializing Scrive: Failed to execute 'appendChild' on 'Node': This node type does not support this method." And does not work.